#!/system/bin/sh
# ============================================================
# gsi_survival_check.sh
# Vendor15 Compatibility Lifetime Extension — Boot Gate
# ============================================================
#
# Called from gsi_survival.rc during post-fs-data.
# Performs upgrade/downgrade detection, SDK version tracking,
# and cache sanitation for safe userdata-preserving upgrades.
#
# Exit codes:
#   0 = normal boot or upgrade detected (safe to continue)
#   1 = downgrade detected (caller must halt boot)
#
# Properties set:
#   persist.sys.prev_sdk         — last successfully booted SDK version
#   persist.sys.gsi_upgrade      — "1" during the one upgrade boot
#   sys.gsi.boot_decision        — "normal" | "upgrade" | "downgrade"
# ============================================================

LOG_TAG="GSI_SURVIVAL"

log_info()  { log -t "$LOG_TAG" -p i "$1"; echo "$1" > /dev/kmsg; }
log_warn()  { log -t "$LOG_TAG" -p w "$1"; echo "$1" > /dev/kmsg; }
log_fatal() { log -t "$LOG_TAG" -p f "$1"; echo "$1" > /dev/kmsg; }

# -------------------------------------------------------
# 1. Read current and previous SDK versions
# -------------------------------------------------------
CURRENT_SDK=$(getprop ro.build.version.sdk)
PREV_SDK=$(getprop persist.sys.prev_sdk)

log_info "=== GSI Survival Boot Gate ==="
log_info "Current SDK : ${CURRENT_SDK:-(empty)}"
log_info "Previous SDK: ${PREV_SDK:-(empty/first boot)}"

# Sanity: if current SDK is unreadable, something is deeply wrong
if [ -z "$CURRENT_SDK" ]; then
    log_fatal "FATAL: ro.build.version.sdk is empty. Cannot determine OS version."
    setprop sys.gsi.boot_decision "error"
    exit 1
fi

# -------------------------------------------------------
# 2. First-ever boot (no previous SDK recorded)
# -------------------------------------------------------
if [ -z "$PREV_SDK" ]; then
    log_info "First boot detected (no persist.sys.prev_sdk)."
    log_info "Recording SDK ${CURRENT_SDK} as baseline."
    setprop persist.sys.prev_sdk "$CURRENT_SDK"
    setprop sys.gsi.boot_decision "first_boot"
    # No cache wipe on first boot — nothing stale exists
    exit 0
fi

# -------------------------------------------------------
# 3. Downgrade detection (FATAL — block boot)
# -------------------------------------------------------
if [ "$CURRENT_SDK" -lt "$PREV_SDK" ] 2>/dev/null; then
    log_fatal "=== DOWNGRADE DETECTED ==="
    log_fatal "Current SDK ${CURRENT_SDK} < Previous SDK ${PREV_SDK}"
    log_fatal "Downgrade is FORBIDDEN: database schemas, keystore, and"
    log_fatal "FBE metadata are forward-migrated and cannot be rolled back."
    log_fatal "Options:"
    log_fatal "  1. Flash the same or newer GSI (SDK >= ${PREV_SDK})"
    log_fatal "  2. Factory reset (wipe userdata) to use this GSI"
    log_fatal "==========================="
    setprop sys.gsi.boot_decision "downgrade"
    # persist.sys.prev_sdk is NOT updated — it preserves the high-water mark
    exit 1
fi

# -------------------------------------------------------
# 4. Same-version boot (normal)
# -------------------------------------------------------
if [ "$CURRENT_SDK" -eq "$PREV_SDK" ] 2>/dev/null; then
    log_info "Same SDK version (${CURRENT_SDK}). Normal boot."
    setprop sys.gsi.boot_decision "normal"
    # In case a previous upgrade left the flag (shouldn't happen, but belt+suspenders)
    if [ "$(getprop persist.sys.gsi_upgrade)" = "1" ]; then
        log_warn "Clearing stale persist.sys.gsi_upgrade from previous boot."
        setprop persist.sys.gsi_upgrade "0"
    fi
    exit 0
fi

# -------------------------------------------------------
# 5. Upgrade detected (current > previous)
# -------------------------------------------------------
log_info "=== UPGRADE DETECTED ==="
log_info "SDK ${PREV_SDK} -> ${CURRENT_SDK}"
setprop sys.gsi.boot_decision "upgrade"

# Check if cleanup already ran for this upgrade (one-shot guard)
if [ "$(getprop persist.sys.gsi_upgrade)" = "1" ]; then
    log_warn "persist.sys.gsi_upgrade already set. Cleanup already ran. Skipping."
    # Still update prev_sdk in case it wasn't persisted last time
    setprop persist.sys.prev_sdk "$CURRENT_SDK"
    setprop persist.sys.gsi_upgrade "0"
    exit 0
fi

# Signal that this is the one upgrade boot
setprop persist.sys.gsi_upgrade "1"

# -------------------------------------------------------
# 6. Cache sanitation (safe items ONLY)
# -------------------------------------------------------
log_info "--- Cache sanitation starting ---"

# SAFE TO REMOVE: dalvik-cache (regenerated by dex2oat on boot)
if [ -d /data/dalvik-cache ]; then
    rm -rf /data/dalvik-cache/*
    log_info "Cleared /data/dalvik-cache/"
else
    log_info "/data/dalvik-cache/ does not exist, skipping."
fi

# SAFE TO REMOVE: resource cache (regenerated by framework)
if [ -d /data/resource-cache ]; then
    rm -rf /data/resource-cache/*
    log_info "Cleared /data/resource-cache/"
else
    log_info "/data/resource-cache/ does not exist, skipping."
fi

# SAFE TO REMOVE: package cache (PackageManager rebuilds this)
if [ -d /data/system/package_cache ]; then
    rm -rf /data/system/package_cache/*
    log_info "Cleared /data/system/package_cache/"
else
    log_info "/data/system/package_cache/ does not exist, skipping."
fi

# EXPLICITLY PRESERVED (do NOT touch):
#   /data/system/*          — PackageManager DB, settings, users
#   /data/misc/vold         — FBE keys and volume metadata
#   /data/misc/keystore     — app and system credential storage
#   /metadata               — dm-verity state, checkpoint data
log_info "Preserved: /data/system/*, /data/misc/vold, /data/misc/keystore, /metadata"

log_info "--- Cache sanitation complete ---"

# -------------------------------------------------------
# 7. Record the new SDK as the high-water mark
# -------------------------------------------------------
setprop persist.sys.prev_sdk "$CURRENT_SDK"
log_info "Updated persist.sys.prev_sdk to ${CURRENT_SDK}"
log_info "=== Upgrade processing complete. Continuing boot. ==="

exit 0
