#!/usr/bin/env python3
"""
Mapper v5 Shim Generator for Vendor15 Survival Architecture.

Generates a C++ shim library that wraps a vendor's native mapper v4.0
implementation and exposes it as a mapper v5.0 interface. This allows
Android 17+ SurfaceFlinger/libui (which require mapper v5.0) to work
with Vendor15 devices that only provide mapper v4.0.

This is ONLY for native passthrough HALs loaded via dlopen().
Binder-based AIDL HALs cannot be shimmed this way.

Usage:
    python3 generate_mapper_shim.py \
        --vendor-version 4 \
        --target-version 5 \
        --output-dir /path/to/output/

Output:
    mapper_v5_shim.cpp   — shim implementation
    mapper_v5_shim.h     — shim header
    Android.bp           — build integration
    README.md            — build instructions
"""

import argparse
import os
import sys
import textwrap
from pathlib import Path


# ============================================================
# Mapper v4 → v5 API surface knowledge
# ============================================================
# These are the key functions in the gralloc/mapper interface.
# v4 and v5 share a common base; v5 adds a few new methods.

MAPPER_V4_FUNCTIONS = [
    ("AIMapper_Error", "importBuffer",
     "const native_handle_t* _Nonnull handle, buffer_handle_t* _Nonnull outBuffer"),
    ("AIMapper_Error", "freeBuffer",
     "buffer_handle_t _Nonnull buffer"),
    ("AIMapper_Error", "getTransportSize",
     "buffer_handle_t _Nonnull buffer, uint32_t* _Nonnull outNumFds, uint32_t* _Nonnull outNumInts"),
    ("AIMapper_Error", "lock",
     "buffer_handle_t _Nonnull buffer, uint64_t cpuUsage, ARect accessRegion, "
     "int acquireFence, void* _Nullable* _Nonnull outData"),
    ("AIMapper_Error", "unlock",
     "buffer_handle_t _Nonnull buffer, int* _Nonnull outReleaseFence"),
    ("AIMapper_Error", "flushLockedBuffer",
     "buffer_handle_t _Nonnull buffer"),
    ("AIMapper_Error", "rereadLockedBuffer",
     "buffer_handle_t _Nonnull buffer"),
    ("AIMapper_Error", "getMetadata",
     "buffer_handle_t _Nonnull buffer, AIMapper_MetadataType metadataType, "
     "void* _Nullable destBuffer, size_t destBufferSize"),
    ("AIMapper_Error", "setMetadata",
     "buffer_handle_t _Nonnull buffer, AIMapper_MetadataType metadataType, "
     "const void* _Nonnull metadata, size_t metadataSize"),
    ("AIMapper_Error", "listSupportedMetadataTypes",
     "const AIMapper_MetadataTypeDescription* _Nullable* _Nonnull outDescriptions, "
     "size_t* _Nonnull outCount"),
    ("AIMapper_Error", "dumpBuffer",
     "buffer_handle_t _Nonnull buffer, AIMapper_DumpBufferCallback _Nonnull callback, "
     "void* _Nullable context"),
    ("AIMapper_Error", "dumpAllBuffers",
     "AIMapper_BeginDumpBufferCallback _Nonnull beginCallback, "
     "AIMapper_DumpBufferCallback _Nonnull dumpCallback, void* _Nullable context"),
    ("AIMapper_Error", "getStandardMetadata",
     "buffer_handle_t _Nonnull buffer, int64_t standardMetadataType, "
     "void* _Nullable destBuffer, size_t destBufferSize"),
    ("AIMapper_Error", "setStandardMetadata",
     "buffer_handle_t _Nonnull buffer, int64_t standardMetadataType, "
     "const void* _Nonnull metadata, size_t metadataSize"),
]

# v5-only methods that have no v4 equivalent — return UNSUPPORTED
MAPPER_V5_ADDITIONS = [
    ("AIMapper_Error", "getReservedRegion",
     "buffer_handle_t _Nonnull buffer, void* _Nullable* _Nonnull outReservedRegion, "
     "uint64_t* _Nonnull outReservedSize",
     "AIMAPPER_ERROR_UNSUPPORTED"),
]


def generate_header(vendor_ver: int, target_ver: int) -> str:
    """Generate the shim header file."""
    return textwrap.dedent(f"""\
        /*
         * AUTO-GENERATED by generate_mapper_shim.py
         * Mapper v{target_ver} shim wrapping vendor v{vendor_ver}
         *
         * DO NOT EDIT MANUALLY
         */
        #pragma once

        #include <android/hardware/graphics/mapper/utils/IMapperProvider.h>
        #include <dlfcn.h>
        #include <log/log.h>

        #define SHIM_LOG_TAG "MapperV{target_ver}Shim"

        namespace android::hardware::graphics::mapper::shim {{

        /**
         * Mapper v{target_ver} shim that delegates to vendor's v{vendor_ver} implementation.
         *
         * This shim is loaded by libui when it looks for mapper v{target_ver}.0.
         * It internally dlopen's the vendor's v{vendor_ver}.0 mapper and translates
         * v{target_ver} calls to v{vendor_ver} calls.
         *
         * For v{target_ver} methods that have no v{vendor_ver} equivalent, the shim
         * returns AIMAPPER_ERROR_UNSUPPORTED, allowing the framework to degrade
         * gracefully.
         */

        class MapperV{target_ver}Shim {{
        public:
            static MapperV{target_ver}Shim& getInstance();

            bool isLoaded() const {{ return mHandle != nullptr; }}

            // v{vendor_ver} functions (delegated)
            AIMapper_Error importBuffer(const native_handle_t* handle,
                                        buffer_handle_t* outBuffer);
            AIMapper_Error freeBuffer(buffer_handle_t buffer);
            AIMapper_Error lock(buffer_handle_t buffer, uint64_t cpuUsage,
                               ARect accessRegion, int acquireFence,
                               void** outData);
            AIMapper_Error unlock(buffer_handle_t buffer, int* outReleaseFence);
            AIMapper_Error getTransportSize(buffer_handle_t buffer,
                                            uint32_t* outNumFds,
                                            uint32_t* outNumInts);

            // v{target_ver}-only functions (return UNSUPPORTED)
            AIMapper_Error getReservedRegion(buffer_handle_t buffer,
                                             void** outReservedRegion,
                                             uint64_t* outReservedSize);

        private:
            MapperV{target_ver}Shim();
            ~MapperV{target_ver}Shim();

            bool loadVendorMapper();

            void* mHandle = nullptr;  // dlopen handle

            // Function pointers to vendor v{vendor_ver} implementation
            using ImportBufferFunc = AIMapper_Error (*)(const native_handle_t*, buffer_handle_t*);
            using FreeBufferFunc = AIMapper_Error (*)(buffer_handle_t);
            using LockFunc = AIMapper_Error (*)(buffer_handle_t, uint64_t, ARect, int, void**);
            using UnlockFunc = AIMapper_Error (*)(buffer_handle_t, int*);
            using GetTransportSizeFunc = AIMapper_Error (*)(buffer_handle_t, uint32_t*, uint32_t*);

            ImportBufferFunc mImportBuffer = nullptr;
            FreeBufferFunc mFreeBuffer = nullptr;
            LockFunc mLock = nullptr;
            UnlockFunc mUnlock = nullptr;
            GetTransportSizeFunc mGetTransportSize = nullptr;
        }};

        }}  // namespace android::hardware::graphics::mapper::shim
    """)


def generate_source(vendor_ver: int, target_ver: int) -> str:
    """Generate the shim implementation."""
    # List of vendor .so names to try
    vendor_so_names = [
        f'"mapper.vendor-v{vendor_ver}.0.so"',
        f'"android.hardware.graphics.mapper@{vendor_ver}.0-impl.so"',
        f'"mapper@{vendor_ver}.0-impl.so"',
        f'"hw/mapper.{vendor_ver}.0.so"',
    ]
    vendor_so_list = ",\n        ".join(vendor_so_names)

    return textwrap.dedent(f"""\
        /*
         * AUTO-GENERATED by generate_mapper_shim.py
         * Mapper v{target_ver} shim wrapping vendor v{vendor_ver}
         *
         * DO NOT EDIT MANUALLY
         */

        #include "mapper_v{target_ver}_shim.h"

        #include <dlfcn.h>
        #include <errno.h>
        #include <log/log.h>
        #include <string.h>

        namespace android::hardware::graphics::mapper::shim {{

        MapperV{target_ver}Shim& MapperV{target_ver}Shim::getInstance() {{
            static MapperV{target_ver}Shim instance;
            return instance;
        }}

        MapperV{target_ver}Shim::MapperV{target_ver}Shim() {{
            if (!loadVendorMapper()) {{
                ALOGE("%s: Failed to load vendor mapper v{vendor_ver}. "
                      "Buffer operations will fail.", SHIM_LOG_TAG);
            }} else {{
                ALOGI("%s: Successfully loaded vendor mapper v{vendor_ver} shim.",
                      SHIM_LOG_TAG);
            }}
        }}

        MapperV{target_ver}Shim::~MapperV{target_ver}Shim() {{
            if (mHandle) {{
                dlclose(mHandle);
                mHandle = nullptr;
            }}
        }}

        bool MapperV{target_ver}Shim::loadVendorMapper() {{
            // Try multiple possible .so names for vendor mapper v{vendor_ver}
            const char* soNames[] = {{
                {vendor_so_list}
            }};

            for (const char* soName : soNames) {{
                ALOGI("%s: Trying to load vendor mapper: %s", SHIM_LOG_TAG, soName);

                // RTLD_NOW: resolve all symbols immediately to fail fast
                // RTLD_LOCAL: don't pollute global symbol namespace
                mHandle = dlopen(soName, RTLD_NOW | RTLD_LOCAL);
                if (mHandle) {{
                    ALOGI("%s: Loaded vendor mapper: %s", SHIM_LOG_TAG, soName);
                    break;
                }}

                ALOGW("%s: dlopen(%s) failed: %s", SHIM_LOG_TAG, soName, dlerror());
            }}

            if (!mHandle) {{
                ALOGE("%s: Could not load any vendor mapper v{vendor_ver} .so", SHIM_LOG_TAG);
                return false;
            }}

            // Resolve function pointers
            // The actual symbol names depend on the vendor's export table.
            // Common patterns: AIMapper_loadIMapper, HIDL IMapper methods, etc.
            //
            // For gralloc/mapper v{vendor_ver}, the entry point is typically:
            //   AIMapper_loadIMapper() which returns an AIMapper struct with function pointers
            //
            // We resolve via the standard AIMapper loading mechanism.

            using LoadIMapperFunc = AIMapper_Error (*)(AIMapper* _Nullable* _Nonnull);
            auto loadIMapper = reinterpret_cast<LoadIMapperFunc>(
                dlsym(mHandle, "AIMapper_loadIMapper"));

            if (!loadIMapper) {{
                ALOGE("%s: AIMapper_loadIMapper not found in vendor .so: %s",
                      SHIM_LOG_TAG, dlerror());
                dlclose(mHandle);
                mHandle = nullptr;
                return false;
            }}

            AIMapper* mapper = nullptr;
            AIMapper_Error err = loadIMapper(&mapper);
            if (err != AIMAPPER_ERROR_NONE || !mapper) {{
                ALOGE("%s: AIMapper_loadIMapper failed: %d", SHIM_LOG_TAG, err);
                dlclose(mHandle);
                mHandle = nullptr;
                return false;
            }}

            // Extract function pointers from the AIMapper struct
            mImportBuffer = mapper->v5.importBuffer ?
                mapper->v5.importBuffer : mapper->importBuffer;
            mFreeBuffer = mapper->v5.freeBuffer ?
                mapper->v5.freeBuffer : mapper->freeBuffer;
            mLock = mapper->v5.lock ? mapper->v5.lock : mapper->lock;
            mUnlock = mapper->v5.unlock ? mapper->v5.unlock : mapper->unlock;
            mGetTransportSize = mapper->v5.getTransportSize ?
                mapper->v5.getTransportSize : mapper->getTransportSize;

            // Validate minimum function set
            if (!mImportBuffer || !mFreeBuffer || !mLock || !mUnlock) {{
                ALOGE("%s: Vendor mapper missing critical functions", SHIM_LOG_TAG);
                dlclose(mHandle);
                mHandle = nullptr;
                return false;
            }}

            return true;
        }}

        // ============================================================
        // Delegated v{vendor_ver} functions
        // ============================================================

        AIMapper_Error MapperV{target_ver}Shim::importBuffer(
                const native_handle_t* handle, buffer_handle_t* outBuffer) {{
            if (!mImportBuffer) return AIMAPPER_ERROR_UNSUPPORTED;
            return mImportBuffer(handle, outBuffer);
        }}

        AIMapper_Error MapperV{target_ver}Shim::freeBuffer(buffer_handle_t buffer) {{
            if (!mFreeBuffer) return AIMAPPER_ERROR_UNSUPPORTED;
            return mFreeBuffer(buffer);
        }}

        AIMapper_Error MapperV{target_ver}Shim::lock(
                buffer_handle_t buffer, uint64_t cpuUsage,
                ARect accessRegion, int acquireFence, void** outData) {{
            if (!mLock) return AIMAPPER_ERROR_UNSUPPORTED;
            return mLock(buffer, cpuUsage, accessRegion, acquireFence, outData);
        }}

        AIMapper_Error MapperV{target_ver}Shim::unlock(
                buffer_handle_t buffer, int* outReleaseFence) {{
            if (!mUnlock) return AIMAPPER_ERROR_UNSUPPORTED;
            return mUnlock(buffer, outReleaseFence);
        }}

        AIMapper_Error MapperV{target_ver}Shim::getTransportSize(
                buffer_handle_t buffer, uint32_t* outNumFds, uint32_t* outNumInts) {{
            if (!mGetTransportSize) return AIMAPPER_ERROR_UNSUPPORTED;
            return mGetTransportSize(buffer, outNumFds, outNumInts);
        }}

        // ============================================================
        // v{target_ver}-only functions — return UNSUPPORTED
        // ============================================================
        // These methods exist in v{target_ver} but have no v{vendor_ver} equivalent.
        // Returning UNSUPPORTED allows the framework to degrade gracefully.

        AIMapper_Error MapperV{target_ver}Shim::getReservedRegion(
                buffer_handle_t /*buffer*/, void** /*outReservedRegion*/,
                uint64_t* /*outReservedSize*/) {{
            ALOGW("%s: getReservedRegion not supported in vendor v{vendor_ver} shim",
                  SHIM_LOG_TAG);
            return AIMAPPER_ERROR_UNSUPPORTED;
        }}

        }}  // namespace android::hardware::graphics::mapper::shim
    """)


def generate_android_bp(vendor_ver: int, target_ver: int) -> str:
    """Generate Android.bp build file."""
    return textwrap.dedent(f"""\
        // AUTO-GENERATED by generate_mapper_shim.py
        // Mapper v{target_ver} shim wrapping vendor v{vendor_ver}

        cc_library_shared {{
            name: "mapper.v{target_ver}.0-impl-shim",
            relative_install_path: "hw",

            srcs: [
                "mapper_v{target_ver}_shim.cpp",
            ],

            header_libs: [
                "libgralloc_headers",
            ],

            shared_libs: [
                "liblog",
                "libcutils",
                "libutils",
                "libhardware",
                "libdl",
            ],

            cflags: [
                "-Wall",
                "-Werror",
                "-Wno-unused-parameter",
                "-DLOG_TAG=\\"MapperV{target_ver}Shim\\"",
            ],

            // Install to system partition (not vendor)
            vendor: false,
            system_ext_specific: false,

            // SELinux: must be labeled as same_process_hal_file
            // Add to file_contexts:
            //   /system/lib64/hw/mapper\\.v{target_ver}\\.0-impl-shim\\.so  u:object_r:same_process_hal_file:s0
        }}
    """)


def generate_readme(vendor_ver: int, target_ver: int) -> str:
    """Generate README with build instructions."""
    return textwrap.dedent(f"""\
        # Mapper v{target_ver} Shim (wrapping vendor v{vendor_ver})

        ## What This Does

        This shim library allows Android 17+ (which requires mapper v{target_ver}.0)
        to work with Vendor15 devices that only provide mapper v{vendor_ver}.0.

        It is a **native passthrough HAL shim** — a `.so` loaded by `libui` via
        `dlopen()`. It wraps the vendor's v{vendor_ver} mapper and exposes a v{target_ver}
        ABI.

        ## How It Works

        1. `libui` calls `dlopen("mapper.v{target_ver}.0-impl-shim.so")`
        2. The shim's constructor calls `dlopen()` on the vendor's v{vendor_ver} mapper
        3. v{target_ver} API calls are delegated to the vendor's v{vendor_ver} implementation
        4. v{target_ver}-only methods (e.g., `getReservedRegion`) return `UNSUPPORTED`

        ## Building

        ### In AOSP tree:

        ```bash
        # Copy shim source to hardware/interfaces/graphics/mapper/shim/
        cp -r . $AOSP/hardware/interfaces/graphics/mapper/shim/

        # Build
        m mapper.v{target_ver}.0-impl-shim
        ```

        ### Standalone (with NDK):

        Not supported — requires AOSP build system for `libgralloc_headers`.

        ## SELinux

        Add to `system/sepolicy/private/file_contexts`:

        ```
        /system/lib64/hw/mapper\\.v{target_ver}\\.0-impl-shim\\.so  u:object_r:same_process_hal_file:s0
        ```

        ## Verification

        ```bash
        # Check if shim loaded successfully
        adb logcat -d | grep MapperV{target_ver}Shim

        # Check SurfaceFlinger is alive
        adb shell pidof surfaceflinger

        # Check display is rendering
        adb shell dumpsys SurfaceFlinger | grep "Display 0"
        ```

        ## Limitations

        - Only works for **native passthrough** HALs (loaded via `dlopen`)
        - Cannot shim binder-based AIDL HALs (composer3, power, etc.)
        - v{target_ver}-only methods return `UNSUPPORTED` — features that depend
          on them will be unavailable
        - The shim `.so` must be in the system image's linker search path

        ## Generated

        This was auto-generated by `generate_mapper_shim.py`.
        Do NOT edit manually — re-run the generator instead.
    """)


def main():
    parser = argparse.ArgumentParser(
        description="Generate mapper version shim for Vendor15 survival."
    )
    parser.add_argument(
        "--vendor-version", type=int, default=4,
        help="Vendor mapper version (default: 4)",
    )
    parser.add_argument(
        "--target-version", type=int, default=5,
        help="Target mapper version to shim (default: 5)",
    )
    parser.add_argument(
        "--output-dir", type=str, default=".",
        help="Output directory for generated files",
    )

    args = parser.parse_args()
    vendor_ver = args.vendor_version
    target_ver = args.target_version
    output_dir = Path(args.output_dir)

    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Generating mapper v{target_ver} shim (wrapping vendor v{vendor_ver})...")

    # Generate files
    files = {
        f"mapper_v{target_ver}_shim.h": generate_header(vendor_ver, target_ver),
        f"mapper_v{target_ver}_shim.cpp": generate_source(vendor_ver, target_ver),
        "Android.bp": generate_android_bp(vendor_ver, target_ver),
        "README.md": generate_readme(vendor_ver, target_ver),
    }

    for filename, content in files.items():
        filepath = output_dir / filename
        with open(filepath, "w") as f:
            f.write(content)
        print(f"  Created: {filepath}")

    print(f"\nDone. Files written to: {output_dir}")
    print(f"\nNext steps:")
    print(f"  1. Copy to $AOSP/hardware/interfaces/graphics/mapper/shim/")
    print(f"  2. Add SELinux file_contexts entry")
    print(f"  3. Build: m mapper.v{target_ver}.0-impl-shim")
    print(f"  4. Verify: adb logcat | grep MapperV{target_ver}Shim")


if __name__ == "__main__":
    main()
